plugins:
  discourse_templates_enabled:
    default: true
    client: true
  discourse_templates_category:
    default: ""
    type: category
  discourse_templates_max_replies_fetched:
    default: 1000
    hidden: true
